[package]
name = "eth-riscv-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
eth-riscv-syscalls = { path = "../eth-riscv-syscalls" }
riscv-rt = "0.12.2"

alloy-core = { version = "0.7.4", default-features = false }
alloy-sol-types = { version = "0.7.4", default-features = false }
